/********************************************************************
* tnp/anaTNP2Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error tnp/anaTNP2Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableanaTNP2Dict();
extern void G__cpp_setup_inheritanceanaTNP2Dict();
extern void G__cpp_setup_typetableanaTNP2Dict();
extern void G__cpp_setup_memvaranaTNP2Dict();
extern void G__cpp_setup_globalanaTNP2Dict();
extern void G__cpp_setup_memfuncanaTNP2Dict();
extern void G__cpp_setup_funcanaTNP2Dict();
extern void G__set_cpp_environmentanaTNP2Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "tnp/anaTNP2.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__anaTNP2DictLN_TClass;
extern G__linked_taginfo G__anaTNP2DictLN_TBuffer;
extern G__linked_taginfo G__anaTNP2DictLN_TMemberInspector;
extern G__linked_taginfo G__anaTNP2DictLN_TObject;
extern G__linked_taginfo G__anaTNP2DictLN_string;
extern G__linked_taginfo G__anaTNP2DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__anaTNP2DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__anaTNP2DictLN_TString;
extern G__linked_taginfo G__anaTNP2DictLN_TLatex;
extern G__linked_taginfo G__anaTNP2DictLN_TBox;
extern G__linked_taginfo G__anaTNP2DictLN_TLegendEntry;
extern G__linked_taginfo G__anaTNP2DictLN_TLegend;
extern G__linked_taginfo G__anaTNP2DictLN_TLine;
extern G__linked_taginfo G__anaTNP2DictLN_TArrow;
extern G__linked_taginfo G__anaTNP2DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__anaTNP2DictLN_TFile;
extern G__linked_taginfo G__anaTNP2DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__anaTNP2DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__anaTNP2DictLN_TF1;
extern G__linked_taginfo G__anaTNP2DictLN_TH1D;
extern G__linked_taginfo G__anaTNP2DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__anaTNP2DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__anaTNP2DictLN_TH2D;
extern G__linked_taginfo G__anaTNP2DictLN_TCanvas;
extern G__linked_taginfo G__anaTNP2DictLN_PidTable;
extern G__linked_taginfo G__anaTNP2DictLN_anaTNP2;
extern G__linked_taginfo G__anaTNP2DictLN_vectorlETH1DcOallocatorlETH1DgRsPgR;
extern G__linked_taginfo G__anaTNP2DictLN_reverse_iteratorlEvectorlETH1DcOallocatorlETH1DgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
